FROM  ubuntu:14.04
LABEL maintainer="etvas21@naver.com"
#
RUN echo "root:Docker!" | chpasswd
ENV	DEBIAN_FRONTEND=noninteractive

#RUN 	apt-get install -y software-properties-common
#RUN		add-apt-repository ppa:openjdk-r/ppa
#RUN		apt-get update
#RUN		apt-get install -y openjdk-8-jdk

# To test elasticsearch
RUN		apt-get install -y curl
RUN		apt-get install -y wget

# ppa:personal package archive
RUN apt-get install -y --no-install-recommends software-properties-common && \
		add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get update && \
    (echo openjdk-8-jdk shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections) && \
    apt-get install -y openjdk-8-jdk && \
    rm -rf /var/cache/openjdk-8-jdk && \
    echo "networkaddress.cache.ttl=60" >> /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV		JAVA_HOME	/usr/lib/jvm/java-8-openjdk-amd64

RUN 	groupadd -g 1000 elasticsearch && useradd elasticsearch -u 1000 -g 1000


#elasticsearch 6.x
RUN		wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
RUN		apt-get	install apt-transport-https
RUN		echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
RUN		apt-get update && apt-get install elasticsearch


#LOGSTASH
#RUN		apt-get	install apt-transport-https
#RUN		echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
#RUN		apt-get update && apt-get install logstash

WORKDIR	/usr/share/elasticsearch

RUN set -ex && for path in data logs config config/scripts; do \
        mkdir -p "$path"; \
        chown -R elasticsearch:elasticsearch "$path"; \
    done

# chage to because 6.x
COPY 	logging.yml /usr/share/elasticsearch/config/
COPY 	elasticsearch.yml /etc/elasticsearch/
# below line is to apply 2.x version
#COPY 	elasticsearch.yml /usr/share/elasticsearch/config/
#COPY 	logging.yml /usr/share/elasticsearch/config/

#Install analysis-nori
#RUN		/usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-nori

USER 	elasticsearch

ENV 	PATH=$PATH:/usr/share/elasticsearch/bin
ENV		ES_JAVA_OPTS="$ES_JAVA_OPTS -Djava.io.tmpdir=/usr/tmp"
#ENV 	PATH=$PATH:/usr/share/elasticsearch/config
# Add below line because error "Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root."
#ENV		ES_JAVA_OPTS="-Des.insecure.allow.root=true"
#ENV		ES_PATH_CONF=/usr/share/elasticsearch/config

#CMD 	["elasticsearch"]

#EXPOSE	9200 9300


##################################################
# Solved : memory error
# http://www.pradeepadiga.me/blog/2017/02/27/elasticsearch-fails-to-start-with-cannot-allocate-memory-error/


##################################################
# run commend
##################################################
# pre-condtion ( volume )
# docker volume create --name esdata
#
# docker run --rm -it -p 9200:9200 -v esdata:/usr/share/elasticsearch/data es
# docker run --rm -ti -p 9200:9200 -v esdata:/usr/share/elasticsearch/data --memory="4g" -e ES_HEAP_SIZE=2g es


# ref site
# https://www.elastic.co/kr/blog/how-to-make-a-dockerfile-for-elasticsearch




#RUN	apt-get update && yes | apt-get upgrade
#RUN	apt-get install -y build-essential

#
#RUN	apt-get -y install vim
#RUN	apt-get -y install wget
#RUN	wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-amd64.deb


# 2.x
#RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 && \
#    add-apt-repository -y "deb http://packages.elastic.co/elasticsearch/6.x/debian stable main" --keyserver https://pgp.mit.edu/ && \
#    apt-get update && \
#    apt-get install -y --no-install-recommends elasticsearch
#
