version: '3.7'

services:
 db:
   container_name: mysql
   image: mysql:8.0.19.02
   restart: always
   #command: --default-authentication-plugin=mysql_native_password
   volumes:
      - mysql_db:/var/lib/mysql
   environment:
      - MYSQL_ROOT_PASSWORD=l@tus
   command: mysqld
   ports:
      - 3306:3306
volumes:
   mysql_db: